-- Init Staging Tables

-- Drop if exists
DROP TABLE IF EXISTS staging_students;
DROP TABLE IF EXISTS staging_performance;

-- Create staging_students with student_id
CREATE TABLE staging_students (
    student_id INT PRIMARY KEY,
    inter_dom TEXT,
    region TEXT,
    gender TEXT,
    academic TEXT,
    age TEXT,
    age_cate TEXT,
    stay TEXT,
    stay_cate TEXT,
    japanese TEXT,
    japanese_cate TEXT,
    english TEXT,
    english_cate TEXT,
    intimate TEXT,
    religion TEXT,
    suicide TEXT,
    dep TEXT,
    deptype TEXT,
    todep TEXT,
    depsev TEXT,
    tosc TEXT,
    apd TEXT,
    ahome TEXT,
    aph TEXT,
    afear TEXT,
    acs TEXT,
    aguilt TEXT,
    amiscell TEXT,
    toas TEXT,
    partner TEXT,
    friends TEXT,
    parents TEXT,
    relative TEXT,
    profess TEXT,
    phone TEXT,
    doctor TEXT,
    reli TEXT,
    alone TEXT,
    others TEXT,
    internet TEXT,
    partner_bi TEXT,
    friends_bi TEXT,
    parents_bi TEXT,
    relative_bi TEXT,
    professional_bi TEXT,
    phone_bi TEXT,
    doctor_bi TEXT,
    religion_bi TEXT,
    alone_bi TEXT,
    others_bi TEXT,
    internet_bi TEXT
);

-- Create staging_performance with student_id
CREATE TABLE staging_performance (
    student_id INT PRIMARY KEY,
    Hours_Studied TEXT,
    Attendance TEXT,
    Parental_Involvement TEXT,
    Access_to_Resources TEXT,
    Extracurricular_Activities TEXT,
    Sleep_Hours TEXT,
    Previous_Scores TEXT,
    Motivation_Level TEXT,
    Internet_Access TEXT,
    Tutoring_Sessions TEXT,
    Family_Income TEXT,
    Teacher_Quality TEXT,
    School_Type TEXT,
    Peer_Influence TEXT,
    Physical_Activity TEXT,
    Learning_Disabilities TEXT,
    Parental_Education_Level TEXT,
    Distance_from_Home TEXT,
    Gender TEXT,
    Exam_Score TEXT
);
